### PR TITLE
Fix compilation errors with `all-features`

### LINKED ISSUE #40: Building fails when selecting `ilp-cbc` feature
Kind of a Rust newbie; sorry if this is a basic misunderstanding!

Here's what I'm seeing when running `cargo build --features ilp-cbc`:

```

error[E0432]: unresolved imports `crate::generate_random_egraph`, `crate::ELABORATE_TESTING`
    --> src/extract/faster_ilp_cbc.rs:1157:34
     |
1157 |         faster_ilp_cbc::extract, generate_random_egraph, ELABORATE_TESTING, EPSILON_ALLOWANCE,
     |                                  ^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^ no `ELABORATE_TESTING` in the root
     |                                  |
     |                                  no `generate_random_egraph` in the root

error[E0107]: struct takes 0 generic arguments but 1 generic argument was supplied
   --> src/main.rs:98:53
    |
98  |                 extractor: extract::faster_ilp_cbc::FasterCbcExtractor::<10>.boxed(),
    |                                                     ^^^^^^^^^^^^^^^^^^------ help: remove these generics
    |                                                     |
    |                                                     expected 0 generic arguments
    |
note: struct defined here, with 0 generic parameters
   --> src/extract/faster_ilp_cbc.rs:184:12
    |
184 | pub struct FasterCbcExtractor;
    |            ^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0107, E0432.
For more information about an error, try `rustc --explain E0107`.
error: could not compile `extraction-gym` (bin "extraction-gym") due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by ninehusky**
Closes #40.

### CODE REVIEW

**Comment by ninehusky** [comment]
@oflatt it's ready for a look!

**Review by oflatt — APPROVED** [review]
looks good

**Comment by ninehusky** [comment]
@oflatt  could we get this merged?

**Comment by oflatt** [comment]
Yeah sorry I forgot

**Pull request merged**
