### PR TITLE
New 'FlexC' dataset

### PR DESCRIPTION
**Pull request by Bastacyclop**

### CODE REVIEW

**Comment by oflatt** [comment]
Do you have a link or description for what these egraphs are?
I think something we should start doing is include a readme.md or description.md in each data set

**Comment by Bastacyclop** [comment]
Hi @oflatt , as mentioned in #7 , the dataset comes from a CGRA mapping tool called 'FlexC': https://arxiv.org/abs/2309.09112. E-graphs in this dataset contain enodes of cost 10_000, which actually means infinity in this context. I can dig up more information if you want: a given CGRA was targeted, applying a given set of rewrite rules to a given an initial e-graph itself derived from the loop body of a given C code.

Having `README.md`s sounds like a good idea.

**Comment by oflatt** [comment]
Oh great! I missed that.
Throw that description into a readme and I'll merge.

**Comment by Bastacyclop** [comment]
README added :)

**Comment by oflatt** [comment]
Thanks!

**Pull request merged**
